### ISSUE TITLE
Center of ScalableLayout

### ISSUE THREAD

**Issue by lapnd** [ssomai/ScalableLayout#18]
Hi Ssomai,
Thank for your library.
I have a question. In the ScalableLayout, how can we put a view in the center of this layout?
For example, in the scalable layout, I have 3 view: PreviousButton ---- TextView -----NextButton
The content of textview is changed dynamically. How to ensure this text is alway the center of the layout?
(Like RelaytiveLayout)
Thank

**Comment by ssomai** [comment]
I'm sorry for late update.

I Implemented TextView_WrapContent_Direction.Center_Vertical.
But I can't make TextView_WrapContent_Direction.Center, because I can't decide which direction is right to expand.

Thanks. :)
