### ISSUE TITLE
xml에서 textview_wrapcontent_resizesurrounded 에러

### ISSUE THREAD

**Issue by lsb156** [ssomai/ScalableLayout#19]
안녕하세요 ScalableLayout로 어플만들고있습니다.
그런데 버그가 있는거 같아서 문의 드립니다.
XML 내에서 텍스트 사이즈를 딱 맞게 줄이려고
sl:textview_wrapcontent_direction="right"
sl:textview_wrapcontent_resizesurrounded="true" 로 쓰고있는데
그 부모들의 left나 top가 1이라도 있는 경우 출력자체가 안되는 버그가 있습니다.
부모뿐만 아니라 부모의 부모를 쭉 타고가서 루트까지 전부 left top이 0이여야 제대로 보여지는 현상이 있어서 이슈 적어봅니다.

**Comment by ssomai** [comment]
ㅠㅠㅠㅠㅠㅠㅠ 죄송합니다. 
요즘 다사다난하다보니... ㅠㅠㅠ
계속 확인이 늦어지고 있습니다 ㅠㅠㅠㅠ

빨리 확인 드리고 다시 코멘트 달겠습니다 ㅠㅠㅠㅠㅠㅠㅠ

**Comment by ssomai** [comment]
오 확인해보니까
중간쯤에 
 <LinearLayout
    android:layout_width="0dp"
    android:layout_height="wrap_content"
    android:layout_weight="314"
    android:orientation="vertical" >
에서 layout_width="0dp" 라서 인것 같아요.
그래서
 <LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_weight="314"
    android:orientation="vertical" >
로 바꾸니까 잘 나와요~ ㅎ
