### ISSUE TITLE
레이아웃 크기 설정 질문입니다.

### ISSUE THREAD

**Issue by kys9261** [ssomai/ScalableLayout#22]
샘플 코드중에 아래와 같은 코드가 있는데

// 상대적인 단위로 pixel 이나 dp 단위가 아닙니다.
ScalableLayout sl = new ScalableLayout(this, 400, 200);

여기서 400,200이 의미하는게 가로가 400, 세로가 200이니까 1:0.5 비율이라고 보고
화면의 해상도가 만약에 가로가 720 이고 세로가 1280일때 1:0.5을 적용시켜서
저 위의 레이아웃은 단말기에서 가로가 720이고 세로가 360이 되는건가요??

저 사이즈를 어떻게 가늠해야할지 잘 모르겠습니다.

**Comment by ssomai** [comment]
네, 말씀하신게 맞습니다! ㅎㅎ
ScalableLayout은 지정받은 비율대로 커지거나 작아집니다.
