### ISSUE TITLE
안녕하세요...xml파일에서 오류나요ㅜㅜ

### ISSUE THREAD

**Issue by hjsuh** [ssomai/ScalableLayout#23]
ScalableLayout임포트하고요 xml샘플 그대로넣어봤는데요..텍스트뷰랑랑 이미지뷰 부분에서 전부 에러뜨네요ㅜ.ㅜAttribute is missing the Android namespace prefix 이에러요!!오타도 한개도 없는데..오ㅐ이러는걸까요 도와주시면 감사하겠습니다!

**Comment by hjsuh** [comment]
ㅇㅏ..메니페스트에     xmlns:sl="http://schemas.android.com/apk/res/com.ssomai.android.scalablelayout"
이거추가하니까 저 에러는 없어졌네요.......근데데 또다른 에러가 생겼어요..ㅠ.ㅠ
<com.ssomai.android.scalablelayout.ScalableLayout 이부분에 parsing XML: unbound prefix
이 에러가 나네요....이건 왜일까요ㅜㅠ

**Comment by ssomai** [comment]
안녕하세요~ 

혹시 Android Studio 쓰시나요?
그럼 dependencies에 

    dependencies {
        compile 'com.ssomai:android.scalablelayout:2.0.0'
    }

만 추가하시면 사용하시기 편하실거에요~.

그리고 eclipse 쓰시고, 소스를 그대로 import하신거면, 거기서 고치셔야 되는부분이 
xmlns:sl="http://schemas.android.com/apk/res/<com.ssomai.android.scalablelayout>"
<com.ssomai.android.scalablelayout> 이 부분입니다~
이 쪽은 개발하시는 앱의 app package를 넣으시면 됩니다~.

해보시고 또 안되시면 알려주세요~

**Comment by hjsuh** [comment]
오!!!!이클립스였고요 해결했어요!!!!프로젝트주소.ScalableLayout 쓸때 대문자로 쓰면 되요!!!ㅜㅜ그냥 철자오류였나봐요ㅠㅠ............
정말정말감사합니다!!!1ㅜㅜㅜㅜ만수무강하세요!!!

**Comment by ssomai** [comment]
아하 다행이네요! ㅎㅎ 감사합니다~ ^^
개발자님도 만수무강하세요 ㅎㅎ
