### ISSUE TITLE
중앙정렬에 대해

### ISSUE THREAD

**Issue by only2433** [ssomai/ScalableLayout#25]
<com.littlefox.mp4enc.view.ScalableLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        sl:scale_base_height="800"
        sl:scale_base_width="1280">

        <ProgressBar
            android:id="@+id/pb_player"
            style="?android:attr/progressBarStyleInverse"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:indeterminate="true"
            android:visibility="visible"
            sl:scale_width="120"
        	sl:scale_height="120"
        	sl:scale_left = "640"
        	sl:scale_top = "370"
            />
    </com.littlefox.mp4enc.view.ScalableLayout>

이러한 코드로 폰과 태블릿 중앙에 프로그래스를 위치시키려하는데

폰과 태블릿이 좀 어긋납니다. 위치가

폰은 겔럭시 S4 (1920 x 1280) 을 사용하였으며
태블릿은 겔럭시 노트 프로 10.1 (2560 x 1600) 을 사용하였습니다.

폰 위치를 맞췃는데 태블릿 위치가 좀 중앙에서 오른쪽 밑으로 치우칩니다.
어떻게 수정하면 될까요?

**Comment by ssomai** [comment]
헉, 그렇군요! 이슈 알려주셔서 감사합니다!

제가... 갤럭시 노트 프로가 없어서... ㅠㅠㅠㅠ

아, 스크린샷 찍어서 올려주시면, 바로 확인해봐드릴수 있을것 같습니다. ^^

감사합니다!!!

**Comment by ssomai** [comment]
아;; 공개되기 어려운 스크린샷이라면,

제 이메일로 보내주셔도 됩니다~~ ㅎ
