### ISSUE TITLE
안드로이드 스튜디오 렌더링 오류

### ISSUE THREAD

**Issue by Ganggroid** [ssomai/ScalableLayout#26]
![image](https://cloud.githubusercontent.com/assets/5188404/7215990/da9e7a3a-e628-11e4-83b3-783a6fb063fc.png)

이런식으로 렌더링 오류가 뜹니다.
어떻게 해야 하나요..

**Comment by ssomai** [comment]
헉 전 잘 되는데... ㅠㅠ
다음 두가지 사항 확인해봐주세요~.

app.gradle에서
dependencies {
    ...
    compile 'com.ssomai:android.scalablelayout:2.0.0'
}

layout xml에서 최상위 layout에
    xmlns:sl="http://schemas.android.com/apk/res-auto"
넣으셨는지..

확인부탁드릴게요~.

**Comment by Ganggroid** [comment]
@ssomai 넣어져 있는데 그러네요.. ㅠㅠ
![image](https://cloud.githubusercontent.com/assets/5188404/7219431/c42ecaae-e6da-11e4-9376-bd10fe00bc3a.png)
![image](https://cloud.githubusercontent.com/assets/5188404/7219434/cc52fcf0-e6da-11e4-83bf-dfd1ec9b6c29.png)
![image](https://cloud.githubusercontent.com/assets/5188404/7219439/f4116434-e6da-11e4-9c32-702ad7841bdb.png)

**Comment by ssomai** [comment]
저 에러는 테마세팅쪽인것 같애요~
사용 sdk 버전을 올려보세요~.
