### ISSUE TITLE
Other Elements Support

### ISSUE THREAD

**Issue by online-lorno** [ssomai/ScalableLayout#27]
Is there a way or do you have any example that this is applicable to elements like buttons, textboxes and the like. It seems that only the TextView and ImageView is supported for this(correct me if I'm wrong). TIA

**Comment by ssomai** [comment]
You can use any views easily like buttons and textboxes and so on, because ScalableLayout support any views.

**Comment by online-lorno** [comment]
Okay noted on that. I had some problems opening the sample project on my Android Studio, where do I put
```groovy
dependencies {
  compile 'com.ssomai:android.scalablelayout:2.0.0'
}
```

Is it on the project build.gradle or sample_scalablelayout build.gradle?

**Comment by ssomai** [comment]
I think that it would be on the project build.gradle.

**Comment by online-lorno** [comment]
I added it on the sample_scalablelayout gradle file since it's not working on the project gradle file. I will look into that more. Thanks.

**Comment by ssomai** [comment]
Thank you for your experience.
I hope that ScalableLayout helps you well.

**Comment by online-lorno** [comment]
So to add other elements like buttons and textboxes, you have to do it manually into the Activity Class and not through the layout file?

**Comment by ssomai** [comment]
you can add buttons and textboxes in Activity class, and also through the layout file.
