### ISSUE TITLE
TextSwitcher를 활용할 수는 없을까요?

### ISSUE THREAD

**Issue by mg2000** [ssomai/ScalableLayout#29]
TextSwitcher를 ScalableLayout에서 사용해보려고 하는데, 배치하는 것은 문제가 없지만, text size를 정해 주려고 하면, TextSwitcher 안에 있는 TextView의 text size를 바꿔야 하는데, 이 TextView가 ScalableLayout에 속해있지 않는다는 에러가 뜨는군요.

TextSwitcher의 text size도 ScalableLayout을 통해 바꿀 수 있을까요?

**Comment by ssomai** [comment]
안녕하세요~.

아쉽게도 ScalableLayout에서의 scale 속성값들(scale_textsize 포함)
그 ScalableLayout의 바로 밑에 있는 view들에 대해서만 적용이 됩니다.

그래서 ScalableLayout 밑의 TextSwitcher 밑의 TextView에는 적용이 안 되죠..
해결방법을 고민해보겠습니다 :)

**Comment by mg2000** [comment]
답변 감사드립니다.

TextSwitcher도 지원이 되면 좀 더 활용 범위가 넓어지지 않을까 생각을 해봤습니다. ^^
