### ISSUE TITLE
오픈소스 프로젝트 디펜더시 설정

### ISSUE THREAD

**Issue by DohyukKim** [ssomai/ScalableLayout#31]
안녕하세요, 안드로이드 앱 공부를 하는 학생입니다.

우연히 scalableLayout을 알게되서 살펴보려고 하는데요,

오픈소스 프로젝트에 디펜더시 설정하려고 

sample_scalablelayout > build.gradle에 

dependencies {
  compile 'com.ssomai:android.scalablelayout:2.1.0'
}

디펜더시 설정을 했는데, 

Error:No such property: nexusUsername for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

라는 에러가 납니다. 혹시 잘못 설정한건지 궁금합니다.

감사합니다.

**Comment by ssomai** [comment]
아 그건 libraray_scalablelayout의 maven 업데이트용 코드 때문입니다 ㅎ

sample_scalablelayout > build.gradle 에서
38라인인 compile project(':library_scalablelayout')을
주석처리해보세요.

안 되면 알려주세요~

**Comment by DohyukKim** [comment]
안녕하세요, 답변 감사합니다.

지금 바로 해보았는데요 그래도 같은 에러가 납니다.

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    //compile project(':library_scalablelayout') <-- 38번째 라인 주석처리
    compile 'com.ssomai:android.scalablelayout:2.1.0'
    compile 'com.android.support:appcompat-v7:21.0.2'

//    compile 'com.jayway.android.robotium:robotium-solo:5.2.1'
}

혹시 다른 설정도 필요한지 궁금합니다.

감사합니다.

**Comment by DohyukKim** [comment]
library_scalablelayout의 build.gradle파일에서
46라인 apply from:  '../maven_push.gradle' 주석처리 하니까 되네요.

**Comment by ssomai** [comment]
오 그게 맞는 방법이었군요. ㅎ
감사합니다~~
