### ISSUE TITLE
질문좀요

### ISSUE THREAD

**Issue by tes237** [ssomai/ScalableLayout#32]
(1)다음 2개의 차이가 먼가요?
scale_base_width
scale_width

(2)다음 속성들의 용법이 먼가요?
textview_wrapcontent_direction
textview_wrapcontent_resizesurrounded
textview_wrapcontent_movesiblings

(3)ScalableLayout은 부모 레이아웃에서 써주면 하위 레이아웃들에서도 다 써줘야 하는건가요?

예를들어 애초에 아래와 같은 구조의 레이아웃이 있다면

LinearLayout
--LinearLayout
  ----LinearLayout
    ------TextView
----LinearLayout
    ------TextView
    ------Button

아래처럼 다써줘야 하는건가요?

LinearLayout
--ScalableLayout
   ----LinearLayout
     ------ScalableLayout
         --------LinearLayout
            ----------ScalableLayout
                ------------TextView
   ----LinearLayout
       --------ScalableLayout
           ----------TextView
           ----------Button

**Comment by ssomai** [comment]
안녕하세요.
1. 
scale_base_width는 ScalableLayout의 전체 width 비율값이고,
scale_width는 ScalableLayout의 하위 view들의 width 비율값입니다.

2.
아래 링크를 참조해주세요,
https://github.com/ssomai/ScalableLayout/blob/master/README_ko.md#textview에서-text-내용에-맞춰서-view크기가-변동되게하는-wrapcontent-기능

3.
네, 아래처럼 써줘야 됩니다.
ScalableLayout은 바로 직속의 View들만 layout하기 때문입니다.
그게 당연한게 LinearLayout과 FrameLayout간에 섞어서 쓸때를 생각해봐도 마찬가지죠?
