### ISSUE TITLE
안녕하세요 질문 한 가지 있습니다.

### ISSUE THREAD

**Issue by wonnew1207** [ssomai/ScalableLayout#33]
우선 Scalable 라이브러리 너무 잘 쓰고 있다고 감사하단 말씀 먼저 전해드립니다.

다름이 아니라, 질문이 한 가지 있습니다.

setting 액티비티 레이아웃에서 동적인 레이아웃을 사용하려고 합니다.

ScrollView로 고정 높이를 정해주고

알람 플러스 버튼이 하나만 보이다가 하나 더 추가하면 사진처럼 플러스 버튼이 하나 더 생기면서
레이아웃 크기가 늘어남과 동시에 아래에 배치되어있는 view들은 아래로 밀려나게끔 하고 싶습니다.
알람은 2개까지만 설정하려고 하고있습니다.

![setting](https://cloud.githubusercontent.com/assets/16788128/14704672/d26532c4-07f0-11e6-84b7-9d9af8d22337.png)

제가 생각한 방법으로는 알람 높이라는 변수를 하나 정하고 알람 1이 추가가 되지 않았을때 알람2는 gone으로 보이지 않게 처리하고 알람1이 추가가 되었을때 알람2가 visible 처리 됨과 동시에 고정 높이와 아래 있는 view 들을 알람높이변수 + 해주려고 하는데 이 방법밖에는 없는건가요?

**Comment by ssomai** [comment]
안녕하세요.
그 기능은 LinearLayout을 parent로 만들면 될거 같아요.
vertical로 하고 LinearLayout 밑에 각 버튼들을 ScalableLayout으로 만드는거죠.

이 상태에서는 하나를 gone하면 LinearLayout에 의해서 자동으로 아래에 있는 얘들이 전부 올라갈거에요

**Comment by wonnew1207** [comment]
아하 그런 방법으로 해도 되겠군요 감사합니다.
