### ISSUE TITLE
[요구사항] 좌표 시작을 view의 가운데로 바꿀 수 있을까요

### ISSUE THREAD

**Issue by nihil0821** [ssomai/ScalableLayout#34]
left로 되어 있어서 크기가 다른 view들을 가운데로 정렬 시킬 때마다 크기의 반을 중심 좌표에서 빼줘야해서 불편한 점이 있습니다.

또 view의 크기가 바뀌면 위치도 다시 설정해줘야하는 불편함이 있어서 view의 center에 좌표의 원점이 있는 설정도 있었으면 좋겠습니다. .

**Comment by ssomai** [comment]
오! 좋은 이슈입니다. 
작업하고 말씀드릴게용 :)

**Comment by ssomai** [comment]
오래 기다리셨습니다! 
요청하신 기능 v2.1.1로 릴리즈 하였습니다~ ㅎ
https://github.com/ssomai/ScalableLayout/releases/tag/v2.1.1

**Comment by ssomai** [comment]
혹시 원하신 기능이 아니거나 버그나 에러가 있다면 알려주시면 감사하겠습니다~. :)
