### ISSUE TITLE
style 사용 여부

### ISSUE THREAD

**Issue by sion1116** [ssomai/ScalableLayout#35]
중복되는 속성값들을 템플릿으로 사용하기위해 style이나 dimens를 사용해보려고 하는데
어떻게 하면 될까요?

**Comment by ssomai** [comment]
혹시 그건 style이나 dimens에 resources 태그 안에 
값을 선언하고 난 다음에 그 값을 템플릿으로 사용하면 되지 않을까요? ㅎ
혹시 제가 잘못 이해하고 있다면, 알려주세요~

**Comment by sion1116** [comment]
자답입니다.^^
아래와 같이 사용하니까 되네요.
    styles.xml
    <style name="ScalableStyleTest">
        <item name="scale_height">158</item>
        <item name="scale_width">138</item>
    </style>

    dimens.xml
    <dimen name="logo_text_size">75</dimen>

**Comment by ssomai** [comment]
우와! 샘플까지 같이 올려주시고~~~ 감사합니다~!!! 👍

**Comment by sion1116** [comment]
br태그가 안없어지네요 ㅠㅠ
항상 잘쓰고 있습니다.
감사합니다.^^

**Comment by sion1116** [comment]
다시 클린 빌드해보니 styles은 잘되는데 dimen은 에러가 발생하네요.ㅠㅠ
dimen은 다른 방법을 한번 찾아봐야 겠습니다.

**Comment by sion1116** [comment]
http://blog.danlew.net/2015/01/06/handling-android-resources-with-non-standard-formats/
여기 참고해서 답을 찾았네요.
item으로 등록해서 사용했습니다.
logo_text_size 를 참고해서 보시면 될 것 같네요.
한번 테스트 해보시고 이상없으면 Readme에 추가되면 좋을 것 같네요.
감사합니다.

dimens.xml
![dimen](https://cloud.githubusercontent.com/assets/7803099/15598637/fa84bc38-2416-11e6-805d-d2b05a196bea.png)

사용
![layout](https://cloud.githubusercontent.com/assets/7803099/15598646/124b9f6c-2417-11e6-83c4-c1736347e81d.png)

**Comment by ssomai** [comment]
감사합니다! Readme에 반영하도록 하겠습니다 ㅎ

**Comment by YunHyunJin** [comment]
제가 기존의 코드를 다이나믹 뷰로 변환하는과정에 있는데, 레이아웃이 중첩되어 사용되는 경우에, scalableLayout도 중첩해서 사용이 가능할까요?
