### ISSUE TITLE
Top과 Left

### ISSUE THREAD

**Issue by guswkpro** [ssomai/ScalableLayout#37]
Top과 Left는 java상에서 수정할 수 없나요?
예로
이미지가 있을경우엔 width 300 height 200 인데
이미지가 없고 텍스트만 있으면 width 300 height 50
으로 구성하고싶습니다.
scalablelayout height와 width는 수정이 되는듯한데 
나머지 자식들의 top과 left가 수정이 안되는듯하여 여쭤봅니다

**Comment by guswkpro** [comment]
moveChildView가 잇군요!

**Comment by ssomai** [comment]
감사합니다~ ㅎ 👍 💯
