### ISSUE TITLE
Textview 부분 색상지정 or 크기지정

### ISSUE THREAD

**Issue by guswkpro** [ssomai/ScalableLayout#38]
기존에 있던 TextView에선
SpannableStringBuilder 로 색상 및 크기가 부분적으로 지정이 가능하였는데
ScalableLayout으로 만든 TextView에서는 저게 적용이 되지 않습니다.
다른 방법이 있나요?

**Comment by guswkpro** [comment]
죄송합니다 ㅠㅠ 제 실수때문이엇네요... 잘되네요 하하... 감사합니다!

**Comment by ssomai** [comment]
하핫 잘써주시니 감사합니다! 👍
