### ISSUE TITLE
질문 있습니다.

### ISSUE THREAD

**Issue by juniair** [ssomai/ScalableLayout#40]
scale_left와 scale_top은 마진 비율을 의미하는 것 인가요?

그리고 혹시 각 속성이 어떤 역활을 하는지 래퍼런스 페이지를 추가하는 것은 어떤가요?

**Comment by ssomai** [comment]
scale_left와 scale_top은  이 뷰의 position을 의미 합니다~
여유가 생기는데로 reference page 만들도록 하겠습니다 ㅎ 👍
