### ISSUE TITLE
wrapContent 기능 관련해서 질문 있습니다.

### ISSUE THREAD

**Issue by bsy3719** [ssomai/ScalableLayout#41]
TextView
                android:id="@+id/textview"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                sl:scale_height="55"
                sl:scale_left="50"
                sl:scale_textsize="42"
                sl:scale_top="1220"
                sl:scale_width="950"
                sl:textview_wrapcontent_direction="bottom"
                sl:textview_wrapcontent_movesiblings="true"
                sl:textview_wrapcontent_resizesurrounded="true"

위 텍스트 뷰는 리스트의 항목을 클릭해서 넘어가 자세한 정보를 보여주는 화면에서 사용 하고 있습니다.

어플을 처음 키고 리스트 항목을 클릭해 화면에 들어가면 뷰가 늘어나 있지만

두번째 부터는 뷰가 늘어나있지않고 첫번째 줄만 보여줍니다.

혹시 왜 이런 현상이 일어나는지 원인을 알 수 있을까요??

**Comment by ssomai** [comment]
혹시 textview에 setText하고 난 후에
ScalableLayout View Instance의 requestLayout()이랑 forceLayout()을 호출해봐주실수 있을까요~?

**Comment by bsy3719** [comment]
requestLayout()이랑 forceLayout()을 둘중에 하나만 호출해도 잘됩니다.

몇일 원인을 몰라서 고생했는데 감사합니다.

**Comment by ssomai** [comment]
오! 확인 감사합니다~.
이 문제도 확인해보고 개선이 가능하면 작업해놓겠습니다 👍
