### ISSUE TITLE
와우~~ 정말 멋진 라이브러리입니다.

### ISSUE THREAD

**Issue by taerran** [ssomai/ScalableLayout#42]
다른 블로그에서 ScalableLayout을 소개한 글을 읽고 찾아 왔습니다. 아직 사용해보진 않았지만, 정말 멋진 라이브러리입니다. 
저는 그냥 단순하게 LinearLayout+layout_weight로 무식하게 작업하면 뷰의 크기는 대충 맞출 수 있는데,
뷰에 들어가는 글자 크기는 기기에 따라 좀 작아지기도 하고, 커지기도 해서 영 불만이었습니다.
글자크기도 화면크기에 따라 맞추어 주는 것 같은데, 정말 편할 것 같습니다.

그런데 앱위젯에서는 사용하지 못하겠죠? 앱위젯에서도 비슷한 기능을 구현할 수는 없을까요?

**Comment by ssomai** [comment]
칭찬 감사합니다~. :)

아쉽게도, 제가 앱 위젯을 만들어본적이 없어요~. 
혹시 관련해서 개발을 해보시고 이슈가 있을때 포스팅해주실수 있을까요~?

**Comment by taerran** [comment]
초고속으로 답글 달아주셨네요..^^
잘 아시겠지만, 앱위젯에서는 몇개의 정해진 LayoutGroup과 View밖에는 사용하지 못하잖아요..
ScalableLayout은 FrameLayout을 상속받은 커스텀뷰인데, 커스텀뷰도 앱위젯에서 사용하지 못하니..ㅠ.ㅠ

지금 제 앱에서 문제는, 기본 홈스크린에서는 앱위젯이 깨지지 않고 잘 보이는데, 동일한 기기에서 스마트폰 런처에서 앱위젯을 설치하면 뷰끼리 겹치고 난리가 아니네요..ㅎㅎ

사용해 보고, 나중에 다시 글 올리겠습니다. 수고하세요~~
