### ISSUE TITLE
ScalableLayout 안에 :TextView, ImageView에 id입력시 미리보기 오류

### ISSUE THREAD

**Issue by devjin0617** [ssomai/ScalableLayout#5]
ScalableLayout 안에 TextView등 위젯들을 위치시키고 java파일에서 사용하고 위해

android:id="@+id/ddddddddd" 이런식으로 입력하니깐 미리보기에서 오류가 나서 안보입니다. 실행할때는 문제없는데, XML화면 미리보기가 안되니 불편하기는 합니다 ㅠㅠ

IntelliJ 13 버젼사용하고 있습니다.
# 

```
Rendering Problems 
java.lang.UnsupportedOperationException   at 
android.content.res.BridgeResources.getResourceTypeName(BridgeResources.java:479)   at
 android.view.View.toString(View.java:4017)   at 
com.jnm.android.widget.ScalableLayout.onMeasure(ScalableLayout.java:415)   at 
android.view.View.measure(View.java:16458)   at 
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)   at 
android.widget.FrameLayout.onMeasure(FrameLayout.java:310)   at 
android.view.View.measure(View.java:16458)   at 
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)   at 
android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)   at 
android.widget.LinearLayout.measureVertical(LinearLayout.java:695)   at 
android.widget.LinearLayout.onMeasure(LinearLayout.java:588)   at 
android.view.View.measure(View.java:16458)   at 
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)   at 
android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)   at 
android.widget.LinearLayout.measureVertical(LinearLayout.java:695)   at 
android.widget.LinearLayout.onMeasure(LinearLayout.java:588)   at 
android.view.View.measure(View.java:16458)  
```

**Comment by dec207** [comment]
<RadioGroup
	    android:id="@+id/rg1"
	    android:layout_width="wrap_content"
	    android:layout_height="wrap_content"
	    android:orientation="horizontal"
	    sl:scale_width="1000"
	    sl:scale_height="40"
	    sl:scale_left="0"
	    sl:scale_top="137"
	    sl:scale_textsize="17">
	    <RadioButton
	        android:id="@+id/rb1"
	        android:layout_width="wrap_content"
	        android:layout_height="wrap_content"
	        android:text="text1"
	        android:textSize="17sp" >
	    </RadioButton>
	    
	    <RadioButton 
	        android:id="@+id/rb2"
	        android:layout_width="wrap_content"
	        android:layout_height="wrap_content"
	        android:text="text2"
	        android:textSize="17sp"/>
</RadioGroup>

같은 경우 라디오 그룹 사이즈 자체는 제대로 자리를 잡는데요. 그 그룹내 뷰인 
라디오 버튼은 어떻게 처리를 해야할지.. 괜찮은 팁이 있으시면 좀 부탁드립니다.

**Comment by ssomai** [comment]
안녕하세요!!

질문 올려주셔서 감사합니다.
RadioGroup과 RadioButton의 경우에는
RadioGroup이 LinearLayout이다 보니까
ScalableLayout이 그 안의 RadioButton까지 제어할 수 없는게 현실입니다...

그래서 추천드리는 방법은 
RadioGroup과 RadioButton을 사용하지 않고 CheckBox를 사용해서 직접 Radio기능을 구현하시는 것입니다.

감사합니다!!!

- ps
그리고 다음에 또 문의 주실때는 새로 issue를 생성해서 주시면 감사하겠습니다!! ^^
