### ISSUE TITLE
레이아웃 Preview 화면에서의 에러

### ISSUE THREAD

**Issue by taeyoung4808** [ssomai/ScalableLayout#53]
안녕하세요.
이번 프로젝트를 진행하면서 ScalableLayout을 사용해보려고하는데요,

xml 프리뷰 화면에서 아래와 같은 에러가 나면서 렌더링이 안돼는데, 어떤문제일까요?

AndroidStudio 2.3.3, SDK는 21 사용중입니다.

java.lang.NoSuchFieldError: View_scale_left_baseposition   at com.ssomai.android.scalablelayout.ScalableLayout$LayoutParams.<init>(ScalableLayout.java:938)   at com.ssomai.android.scalablelayout.ScalableLayout.generateLayoutParams(ScalableLayout.java:225)   at com.ssomai.android.scalablelayout.ScalableLayout.generateLayoutParams(ScalableLayout.java:26)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:860)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard   Tip: Try to refresh the layout.

**Comment by ssomai** [comment]
아 늦게 봤네요 혹시 버전이 어떻게 되나요?
2.1.3버전으로 한번 트라이해봐주시겠습니까~?

**Comment by ssomai** [comment]
2.1.6으로 업데이트 해봐주세요~

**Comment by taeyoung4808** [comment]
댓글이 너무 늦었습니다.
2.1.6으로 업데이트 한 후 정상적으로 보여지는부분 확인하였습니다.
좋은 라이브러리 공개해주셔서 감사합니다!
