### ISSUE TITLE
안드로이드스튜디오 2.3.3 사용 시 미리보기 불가 문의

### ISSUE THREAD

**Issue by kimkyungmi** [ssomai/ScalableLayout#54]
안녕하세요, 문의드릴 사항이 있어 글 올립니다.

안드로이드스튜디오 2.3.3 환경에서 ScalableLayout 2.1.3 사용 중에 있습니다.

그런데, xml 파일에서 Preview 영역이 보이지 않습니다.
(아래와 같은 에러가 노출됩니다.)

java.lang.NoSuchFieldError: View_scale_left_baseposition   at com.ssomai.android.scalablelayout.ScalableLayout$LayoutParams.<init>(ScalableLayout.java:914)   at com.ssomai.android.scalablelayout.ScalableLayout.generateLayoutParams(ScalableLayout.java:225)   at com.ssomai.android.scalablelayout.ScalableLayout.generateLayoutParams(ScalableLayout.java:24)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:860)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard   Tip: Try to refresh the layout.

현재 환경은
1. ScalableLayout 사용하는 xml 안에 xmlns:sl="http://schemas.android.com/apk/res-auto" 추가
2. build.gradle 파일 안에 compile 'com.ssomai:android.scalablelayout:2.1.3' 추가
3. Target SDK Version = API 25 : Android 7.1.1 (Nougat)
이렇게 구성되어 있습니다.

(몇일 전까지만 해도 잘 보였는데 갑자기 해당 현상이 발생됩니다...)

혹시 해결방법에 대해 공유해주실 수 있으시면 공유 부탁드립니다.
감사합니다.

**Comment by ssomai** [comment]
안녕하세요~ 리포트 감사합니다 제가 재연이 안 되는데 혹시 재연 가능한 소스 공유 받을수 있을까요?

**Comment by ssomai** [comment]
아 재연했습니다 확인해볼게요~

**Comment by ssomai** [comment]
2.1.6으로 업데이트 해봐주세요~

**Comment by kimkyungmi** [comment]
해결된 점 확인하였습니다.
감사합니다!

**Comment by ssomai** [comment]
감사합니다~ ㅎ
